// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MinervaTG
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
   
        /// <summary>
        /// FirstContact
        /// </summary>
        public void MinervaTestOne()
        {
            #region Variable Declarations
            WinEdit uITxtFirstNameEdit = this.UIMinervaProjectWindow.UITxtFirstNameWindow.UITxtFirstNameEdit;
            WinEdit uITxtLastNameEdit = this.UIMinervaProjectWindow.UITxtLastNameWindow.UITxtLastNameEdit;
            WinEdit uITxtEmailEdit = this.UIMinervaProjectWindow.UITxtEmailWindow.UITxtEmailEdit;
            WinEdit uITextBox1Edit = this.UIMinervaProjectWindow.UITextBox1Window.UITextBox1Edit;
            WinButton uISendButton = this.UIMinervaProjectWindow.UISendWindow.UISendButton;
            #endregion

            // Type 'Felipe' in 'txtFirstName' text box
            uITxtFirstNameEdit.Text = this.MinervaTestOneParams.UITxtFirstNameEditText;

            // Type '{Tab}' in 'txtFirstName' text box
            Keyboard.SendKeys(uITxtFirstNameEdit, this.MinervaTestOneParams.UITxtFirstNameEditSendKeys, ModifierKeys.None);

            // Type 'Morais' in 'txtLastName' text box
            uITxtLastNameEdit.Text = this.MinervaTestOneParams.UITxtLastNameEditText;

            // Type '{Tab}' in 'txtLastName' text box
            Keyboard.SendKeys(uITxtLastNameEdit, this.MinervaTestOneParams.UITxtLastNameEditSendKeys, ModifierKeys.None);

            // Type 'felipe_link64@hotmail.com' in 'txtEmail' text box
            uITxtEmailEdit.Text = this.MinervaTestOneParams.UITxtEmailEditText;

            // Type '{Tab}' in 'txtEmail' text box
            Keyboard.SendKeys(uITxtEmailEdit, this.MinervaTestOneParams.UITxtEmailEditSendKeys, ModifierKeys.None);

            // Type 'this is SPARTAAAAAA!!!' in 'textBox1' text box
            uITextBox1Edit.Text = this.MinervaTestOneParams.UITextBox1EditText;

            // Click 'Send' button
            Mouse.Click(uISendButton, new Point(42, 24));

            // Type 'Felipe' in 'txtFirstName' text box
            uITxtFirstNameEdit.Text = this.MinervaTestOneParams.UITxtFirstNameEditText1;

            // Type '{Tab}' in 'txtFirstName' text box
            Keyboard.SendKeys(uITxtFirstNameEdit, this.MinervaTestOneParams.UITxtFirstNameEditSendKeys1, ModifierKeys.None);

            // Type 'Morais' in 'txtLastName' text box
            uITxtLastNameEdit.Text = this.MinervaTestOneParams.UITxtLastNameEditText1;

            // Type '{Tab}' in 'txtLastName' text box
            Keyboard.SendKeys(uITxtLastNameEdit, this.MinervaTestOneParams.UITxtLastNameEditSendKeys1, ModifierKeys.None);

            // Type 'felipe_link64@hotmail.com' in 'txtEmail' text box
            uITxtEmailEdit.Text = this.MinervaTestOneParams.UITxtEmailEditText1;

            // Type '{Tab}' in 'txtEmail' text box
            Keyboard.SendKeys(uITxtEmailEdit, this.MinervaTestOneParams.UITxtEmailEditSendKeys1, ModifierKeys.None);

            // Type 'This is Sparta!!!' in 'textBox1' text box
            uITextBox1Edit.Text = this.MinervaTestOneParams.UITextBox1EditText1;

            // Click 'Send' button
            Mouse.Click(uISendButton, new Point(31, 15));
        }
        
        #region Properties

        
        public virtual MinervaTestOneParams MinervaTestOneParams
        {
            get
            {
                if ((this.mMinervaTestOneParams == null))
                {
                    this.mMinervaTestOneParams = new MinervaTestOneParams();
                }
                return this.mMinervaTestOneParams;
            }
        }
        
        public UIMinervaProjectWindow UIMinervaProjectWindow
        {
            get
            {
                if ((this.mUIMinervaProjectWindow == null))
                {
                    this.mUIMinervaProjectWindow = new UIMinervaProjectWindow();
                }
                return this.mUIMinervaProjectWindow;
            }
        }
        #endregion
        
        #region Fields
 
        private MinervaTestOneParams mMinervaTestOneParams;
        
        private UIMinervaProjectWindow mUIMinervaProjectWindow;
        #endregion
    }
    

    /// <summary>
    /// Parameters to be passed into 'MinervaTestOne'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class MinervaTestOneParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Felipe' in 'txtFirstName' text box
        /// </summary>
        public string UITxtFirstNameEditText = "Felipe";
        
        /// <summary>
        /// Type '{Tab}' in 'txtFirstName' text box
        /// </summary>
        public string UITxtFirstNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Morais' in 'txtLastName' text box
        /// </summary>
        public string UITxtLastNameEditText = "Morais";
        
        /// <summary>
        /// Type '{Tab}' in 'txtLastName' text box
        /// </summary>
        public string UITxtLastNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'felipe_link64@hotmail.com' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditText = "felipe_link64@hotmail.com";
        
        /// <summary>
        /// Type '{Tab}' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'this is SPARTAAAAAA!!!' in 'textBox1' text box
        /// </summary>
        public string UITextBox1EditText = "this is SPARTAAAAAA!!!";
        
        /// <summary>
        /// Type 'Felipe' in 'txtFirstName' text box
        /// </summary>
        public string UITxtFirstNameEditText1 = "Felipe";
        
        /// <summary>
        /// Type '{Tab}' in 'txtFirstName' text box
        /// </summary>
        public string UITxtFirstNameEditSendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type 'Morais' in 'txtLastName' text box
        /// </summary>
        public string UITxtLastNameEditText1 = "Morais";
        
        /// <summary>
        /// Type '{Tab}' in 'txtLastName' text box
        /// </summary>
        public string UITxtLastNameEditSendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type 'felipe_link64@hotmail.com' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditText1 = "felipe_link64@hotmail.com";
        
        /// <summary>
        /// Type '{Tab}' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditSendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type 'This is Sparta!!!' in 'textBox1' text box
        /// </summary>
        public string UITextBox1EditText1 = "This is Sparta!!!";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMinervaProjectWindow : WinWindow
    {
        
        public UIMinervaProjectWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Minerva Project";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public UITxtFirstNameWindow UITxtFirstNameWindow
        {
            get
            {
                if ((this.mUITxtFirstNameWindow == null))
                {
                    this.mUITxtFirstNameWindow = new UITxtFirstNameWindow(this);
                }
                return this.mUITxtFirstNameWindow;
            }
        }
        
        public UITxtLastNameWindow UITxtLastNameWindow
        {
            get
            {
                if ((this.mUITxtLastNameWindow == null))
                {
                    this.mUITxtLastNameWindow = new UITxtLastNameWindow(this);
                }
                return this.mUITxtLastNameWindow;
            }
        }
        
        public UITxtEmailWindow UITxtEmailWindow
        {
            get
            {
                if ((this.mUITxtEmailWindow == null))
                {
                    this.mUITxtEmailWindow = new UITxtEmailWindow(this);
                }
                return this.mUITxtEmailWindow;
            }
        }
        
        public UITextBox1Window UITextBox1Window
        {
            get
            {
                if ((this.mUITextBox1Window == null))
                {
                    this.mUITextBox1Window = new UITextBox1Window(this);
                }
                return this.mUITextBox1Window;
            }
        }
        
        public UISendWindow UISendWindow
        {
            get
            {
                if ((this.mUISendWindow == null))
                {
                    this.mUISendWindow = new UISendWindow(this);
                }
                return this.mUISendWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITxtFirstNameWindow mUITxtFirstNameWindow;
        
        private UITxtLastNameWindow mUITxtLastNameWindow;
        
        private UITxtEmailWindow mUITxtEmailWindow;
        
        private UITextBox1Window mUITextBox1Window;
        
        private UISendWindow mUISendWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITxtFirstNameWindow : WinWindow
    {
        
        public UITxtFirstNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtFirstName";
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtFirstNameEdit
        {
            get
            {
                if ((this.mUITxtFirstNameEdit == null))
                {
                    this.mUITxtFirstNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtFirstNameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "First";
                    this.mUITxtFirstNameEdit.WindowTitles.Add("Minerva Project");
                    #endregion
                }
                return this.mUITxtFirstNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtFirstNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITxtLastNameWindow : WinWindow
    {
        
        public UITxtLastNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtLastName";
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtLastNameEdit
        {
            get
            {
                if ((this.mUITxtLastNameEdit == null))
                {
                    this.mUITxtLastNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtLastNameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Last";
                    this.mUITxtLastNameEdit.WindowTitles.Add("Minerva Project");
                    #endregion
                }
                return this.mUITxtLastNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtLastNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITxtEmailWindow : WinWindow
    {
        
        public UITxtEmailWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtEmail";
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtEmailEdit
        {
            get
            {
                if ((this.mUITxtEmailEdit == null))
                {
                    this.mUITxtEmailEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtEmailEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Email";
                    this.mUITxtEmailEdit.WindowTitles.Add("Minerva Project");
                    #endregion
                }
                return this.mUITxtEmailEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtEmailEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITextBox1Window : WinWindow
    {
        
        public UITextBox1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox1";
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox1Edit
        {
            get
            {
                if ((this.mUITextBox1Edit == null))
                {
                    this.mUITextBox1Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox1Edit.WindowTitles.Add("Minerva Project");
                    #endregion
                }
                return this.mUITextBox1Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox1Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISendWindow : WinWindow
    {
        
        public UISendWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btSend";
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public WinButton UISendButton
        {
            get
            {
                if ((this.mUISendButton == null))
                {
                    this.mUISendButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISendButton.SearchProperties[WinButton.PropertyNames.Name] = "Send";
                    this.mUISendButton.WindowTitles.Add("Minerva Project");
                    #endregion
                }
                return this.mUISendButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISendButton;
        #endregion
    }
}
