// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MinervaTG
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Estudando uma forma de fechar uma janela modal fora da tela de origem
        /// </summary>
        public void DialogStudy()
        {
            #region Variable Declarations
            WinEdit uITxtFirstNameEdit = this.UIMinervaProjectWindow.UITxtFirstNameWindow.UITxtFirstNameEdit;
            WinEdit uITxtLastNameEdit = this.UIMinervaProjectWindow.UITxtLastNameWindow.UITxtLastNameEdit;
            WinEdit uITxtEmailEdit = this.UIMinervaProjectWindow.UITxtEmailWindow.UITxtEmailEdit;
            WinEdit uITextBox1Edit = this.UIMinervaProjectWindow.UITextBox1Window.UITextBox1Edit;
            WinButton uISendButton = this.UIMinervaProjectWindow.UISendWindow.UISendButton;
            WinButton uIOKButton = this.UIMyApplicationWindow.UIOKWindow.UIOKButton;
            #endregion

            // Type 'Felipe' in 'txtFirstName' text box
            uITxtFirstNameEdit.Text = this.DialogStudyParams.UITxtFirstNameEditText;

            // Type '{Tab}' in 'txtFirstName' text box
            Keyboard.SendKeys(uITxtFirstNameEdit, this.DialogStudyParams.UITxtFirstNameEditSendKeys, ModifierKeys.None);

            // Type 'Morais' in 'txtLastName' text box
            uITxtLastNameEdit.Text = this.DialogStudyParams.UITxtLastNameEditText;

            // Type '{Tab}' in 'txtLastName' text box
            Keyboard.SendKeys(uITxtLastNameEdit, this.DialogStudyParams.UITxtLastNameEditSendKeys, ModifierKeys.None);

            // Type 'felipemsx18@gmail.com' in 'txtEmail' text box
            uITxtEmailEdit.Text = this.DialogStudyParams.UITxtEmailEditText;

            // Type '{Tab}' in 'txtEmail' text box
            Keyboard.SendKeys(uITxtEmailEdit, this.DialogStudyParams.UITxtEmailEditSendKeys, ModifierKeys.None);

            // Type 'This is SPARTA!!!' in 'textBox1' text box
            uITextBox1Edit.Text = this.DialogStudyParams.UITextBox1EditText;
	
			// Click 'Send' button
			Mouse.Click(uISendButton, new Point(21, 15));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(43, 21));
        }
        
        #region Properties
        public virtual DialogStudyParams DialogStudyParams
        {
            get
            {
                if ((this.mDialogStudyParams == null))
                {
                    this.mDialogStudyParams = new DialogStudyParams();
                }
                return this.mDialogStudyParams;
            }
        }
        
        public UIMinervaProjectWindow UIMinervaProjectWindow
        {
            get
            {
                if ((this.mUIMinervaProjectWindow == null))
                {
                    this.mUIMinervaProjectWindow = new UIMinervaProjectWindow();
                }
                return this.mUIMinervaProjectWindow;
            }
        }
        
        public UIMyApplicationWindow UIMyApplicationWindow
        {
            get
            {
                if ((this.mUIMyApplicationWindow == null))
                {
                    this.mUIMyApplicationWindow = new UIMyApplicationWindow();
                }
                return this.mUIMyApplicationWindow;
            }
        }
        #endregion
        
        #region Fields
        private DialogStudyParams mDialogStudyParams;
        
        private UIMinervaProjectWindow mUIMinervaProjectWindow;
        
        private UIMyApplicationWindow mUIMyApplicationWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'DialogStudy'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class DialogStudyParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Felipe' in 'txtFirstName' text box
        /// </summary>
        public string UITxtFirstNameEditText = "Felipe";
        
        /// <summary>
        /// Type '{Tab}' in 'txtFirstName' text box
        /// </summary>
        public string UITxtFirstNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Morais' in 'txtLastName' text box
        /// </summary>
        public string UITxtLastNameEditText = "Morais";
        
        /// <summary>
        /// Type '{Tab}' in 'txtLastName' text box
        /// </summary>
        public string UITxtLastNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'felipemsx18@gmail.com' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditText = "felipemsx18@gmail.com";
        
        /// <summary>
        /// Type '{Tab}' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'This is SPARTA!!!' in 'textBox1' text box
        /// </summary>
        public string UITextBox1EditText = "This is SPARTA!!!";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMinervaProjectWindow : WinWindow
    {
        
        public UIMinervaProjectWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Minerva Project";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public UITxtFirstNameWindow UITxtFirstNameWindow
        {
            get
            {
                if ((this.mUITxtFirstNameWindow == null))
                {
                    this.mUITxtFirstNameWindow = new UITxtFirstNameWindow(this);
                }
                return this.mUITxtFirstNameWindow;
            }
        }
        
        public UITxtLastNameWindow UITxtLastNameWindow
        {
            get
            {
                if ((this.mUITxtLastNameWindow == null))
                {
                    this.mUITxtLastNameWindow = new UITxtLastNameWindow(this);
                }
                return this.mUITxtLastNameWindow;
            }
        }
        
        public UITxtEmailWindow UITxtEmailWindow
        {
            get
            {
                if ((this.mUITxtEmailWindow == null))
                {
                    this.mUITxtEmailWindow = new UITxtEmailWindow(this);
                }
                return this.mUITxtEmailWindow;
            }
        }
        
        public UITextBox1Window UITextBox1Window
        {
            get
            {
                if ((this.mUITextBox1Window == null))
                {
                    this.mUITextBox1Window = new UITextBox1Window(this);
                }
                return this.mUITextBox1Window;
            }
        }
        
        public UISendWindow UISendWindow
        {
            get
            {
                if ((this.mUISendWindow == null))
                {
                    this.mUISendWindow = new UISendWindow(this);
                }
                return this.mUISendWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITxtFirstNameWindow mUITxtFirstNameWindow;
        
        private UITxtLastNameWindow mUITxtLastNameWindow;
        
        private UITxtEmailWindow mUITxtEmailWindow;
        
        private UITextBox1Window mUITextBox1Window;
        
        private UISendWindow mUISendWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITxtFirstNameWindow : WinWindow
    {
        
        public UITxtFirstNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtFirstName";
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtFirstNameEdit
        {
            get
            {
                if ((this.mUITxtFirstNameEdit == null))
                {
                    this.mUITxtFirstNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtFirstNameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "First";
                    this.mUITxtFirstNameEdit.WindowTitles.Add("Minerva Project");
                    #endregion
                }
                return this.mUITxtFirstNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtFirstNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITxtLastNameWindow : WinWindow
    {
        
        public UITxtLastNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtLastName";
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtLastNameEdit
        {
            get
            {
                if ((this.mUITxtLastNameEdit == null))
                {
                    this.mUITxtLastNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtLastNameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Last";
                    this.mUITxtLastNameEdit.WindowTitles.Add("Minerva Project");
                    #endregion
                }
                return this.mUITxtLastNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtLastNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITxtEmailWindow : WinWindow
    {
        
        public UITxtEmailWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtEmail";
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtEmailEdit
        {
            get
            {
                if ((this.mUITxtEmailEdit == null))
                {
                    this.mUITxtEmailEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtEmailEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Email";
                    this.mUITxtEmailEdit.WindowTitles.Add("Minerva Project");
                    #endregion
                }
                return this.mUITxtEmailEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtEmailEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITextBox1Window : WinWindow
    {
        
        public UITextBox1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox1";
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox1Edit
        {
            get
            {
                if ((this.mUITextBox1Edit == null))
                {
                    this.mUITextBox1Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox1Edit.WindowTitles.Add("Minerva Project");
                    #endregion
                }
                return this.mUITextBox1Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox1Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISendWindow : WinWindow
    {
        
        public UISendWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btSend";
            this.WindowTitles.Add("Minerva Project");
            #endregion
        }
        
        #region Properties
        public WinButton UISendButton
        {
            get
            {
                if ((this.mUISendButton == null))
                {
                    this.mUISendButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISendButton.SearchProperties[WinButton.PropertyNames.Name] = "Send";
                    this.mUISendButton.WindowTitles.Add("Minerva Project");
                    #endregion
                }
                return this.mUISendButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISendButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMyApplicationWindow : WinWindow
    {
        
        public UIMyApplicationWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "My Application";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("My Application");
            #endregion
        }
        
        #region Properties
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("My Application");
			object o1 = WinWindow.PropertyNames.AccessibleName;
			object o2 = WinWindow.PropertyNames.AccessibleDescription;
			object o3 = WinWindow.PropertyNames.AccessKey;
			object o4 = WinWindow.PropertyNames.ClassName;

			#endregion
		}

		#region Properties
		public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("My Application");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
